### ISSUE TITLE
Dataset links for ACE05-EN+ and ERE-EN

### ISSUE THREAD

**Issue by zaemyung** [luyaojie/Text2Event#13]
Hi,

Thanks for open sourcing the tool!

I was wondering could you direct me to the links to the **ACE05-EN+** and **ERE-EN** datasets that you've used?
I found the LDC page for the ACE2005 dataset but not for the other two.

Thanks!

**Comment by luyaojie** [comment]
Hi,

I used the above datasets following OneIE.
You  can find more details at https://blender.cs.illinois.edu/software/oneie/The_OneIE_Package.pdf

ACE05-EN+ and ACE05-EN are the same datasets but with different preprocessing methods.

**Comment by xxllp** [comment]
你好 这个ACE05-EN+ 的数据是怎么处理得到的 我找了半天oneIE的代码 没看到具体的描述~~~
