### ISSUE TITLE
小白问一下，能做中文任务吗，T5能支持中文吗

### ISSUE THREAD

**Issue by Josiahhx** [luyaojie/Text2Event#16]
小白问一下，能做中文任务吗，T5能支持中文吗

**Comment by luyaojie** [comment]
你好，支持中文的T5有两种。多语的mT5和中文社区开放的中文T5，后者可以在huggingface的模型库找到。我尝试过都可以开展中文实验。

**Comment by Josiahhx** [comment]
> 

明白了，感谢！
