### ISSUE TITLE
关于ACE05数据集

### ISSUE THREAD

**Issue by zlh-source** [luyaojie/Text2Event#17]
作者你好，我发现ACE05数据集中大半的句子都没有事件信息，对于这些句子需要进行训练吗？如果不训练的话，最终效果是否会下降？

**Comment by luyaojie** [comment]
Hello,

我使用了所有数据进行训练。
印象中参考别的论文汇报结果，保留正例采样负例会有一定的提升。
因为信息抽取的内容通常较为稀疏，一般采样可以较好的平衡正负例，也可以节约GPU时间。

**Comment by zlh-source** [comment]
好的，另外句子编码的时候也是仅在句子上进行编码，而不是在篇章上进行编码？

**Comment by luyaojie** [comment]
是的，我的实验是句子级别的抽取。

**Comment by zlh-source** [comment]
好的，很感谢您的回复！
