### ISSUE TITLE
没有event.schema

### ISSUE THREAD

**Issue by BudBudding** [luyaojie/Text2Event#22]
您好，在readme中提到，运行“bash scripts/processing_data.bash”将自动得到train/dev/test JSON files and event.schema file，我运行之后得到了train_convert/dev_convert/test_convert.json   但是没有event.schema，请问这个文件是自己构建吗？

**Comment by hodorxxx** [comment]
您好，我也遇到了这个问题，请问您最终是自己构造解决的吗
