### ISSUE TITLE
陆老师，想请教下您数据预处理步骤顺序以及原始数据集放置的目录

### ISSUE THREAD

**Issue by chensming** [luyaojie/Text2Event#3]
老师您好，请问是先用Dygiepp处理，然后用OneIE工具处理吗，最开始下载的ACE2005数据集放在哪个目录下呢？(提前感谢~

**Comment by luyaojie** [comment]
Hi，

这两个处理是分开不影响的。
dygiepp仓库中有详细的说明，路径引用正确即可。
oneie可以参考上一个回答。

**Comment by chensming** [comment]
好的谢谢老师！
