### ISSUE TITLE
About the detailed training arguments

### ISSUE THREAD

**Issue by junyi-tiger** [luyaojie/Text2Event#5]
Bravo! I've read the paper and the code in detail. I evaluated the downloaded `dyiepp_ace2005_en_t5_large` model and got `test_trigger-F1 = 72.7273` and `test_role-F1 = 55.0042` . You've really done an outstanding work!  
BTW, could you please tell me how to get the detailed training arguments? I god a mess when I open this file: `dyiepp_ace2005_en_t5_large\training_args.bin`

**Comment by luyaojie** [comment]
Hi,

```
python -c "import torch; print(torch.load('pretrained_models/dyiepp_ace2005_en_t5_large/training_args.bin'))"
```

**Comment by junyi-tiger** [comment]
Thank you! It works.
