### ISSUE TITLE
Run on ace2005 Chinese dataset

### ISSUE THREAD

**Issue by JueXiuHuang** [luyaojie/Text2Event#7]
Hi,
have you ever run the model on ace 2005 chinese dataset?
Can this model support chinese data?
Thanks!

**Comment by luyaojie** [comment]
Hi,
Text2event also supports Chinese datasets.
It will be released soon.

**Comment by JueXiuHuang** [comment]
Thanks for reply!
I'm very looking forward to the result on Chinese datasets and their preprocess details, thanks.
