### ISSUE TITLE
About Model Evaluation

### ISSUE THREAD

**Issue by JueXiuHuang** [luyaojie/Text2Event#9]
Hi,
I have trained the model on ACE2005 dataset and I want to evaluate the model performance.
In `Model Evaluation` block, you give two script related to evaluation, which script should I choose? 

If I have some sentence, how can I get the event table just like the paper shows?
![image](https://user-images.githubusercontent.com/32955131/141241206-c86e9967-71be-43c9-b791-c70030f9495a.png)

Thanks!

**Comment by luyaojie** [comment]
Hi,

1) The reported performance in the paper is computed by `Offset-level Evaluation`.
I selected the model using `record-level Evaluation` during the training stage, and recompute the final result using `Offset-level Evaluation`

2. The prediction of extraction can be implemented with `T5ForConditionalGeneration` and `TreePredictParser`, and I will update the repo later.

**Comment by luyaojie** [comment]
Hi, you can email me, and I will reply to you with the demo code.
